gardener/cert-management

- pkg/controller/issuer/certificate/reconciler.go
keep existing labels and annotations in certificate secret 
```improvement operator
keep existing labels and annotations in certificate secret 
```
> reuse existing secret labels and annotations

- charts/cert-management/templates/deployment.yaml
```improvement operator
Add missing translation from helm values file to controller arguments for 'dns-class' and 'issuer.dns-class' arguments.
```
> overtake 'dns-class' and 'issuer.dns-class' arguments from helm values file

- examples/10-crds.yaml
Adds validation for CRDS. 
Fixes #25 
```improvement operator
Validation for CRDs are added.
```
> Add validation for CRDs

- charts/cert-management/templates/clusterrole.yaml
- charts/cert-management/templates/clusterrolebinding.yaml
- charts/cert-management/templates/role.yaml
- charts/cert-management/templates/rolebinding.yaml
Update RBAC apiVersions. 
/kind cleanup
Fixes #37
```improvement operator
NONE
```
> Update RBAC apiVersions

- build/Dockerfile
update to go v1.15.5
Fixes #
```improvement operator
update to go v1.15.5
```
> update to go v1.15.5

- README.md
Add link to "Request X.509 Certificates" page.
Fixes #68 
```improvement operator
```
> documentation: added link to request certificates in Gardener shoots

- build/Dockerfile
Update Dockerfile base image to alpine:3.13.5
Fixes #
```improvement operator
Update Dockerfile base image to alpine:3.13.5
```
> Update Dockerfile base image to alpine:3.13.5

- pkg/controller/issuer/core/support.go
fix nil pointer dereference in RememberAltIssuerSecret
Fixes #
```bugfix operator
fix nil pointer dereference in RememberAltIssuerSecret if an issuer secret contains no data
```
> fix nil pointer dereference in RememberAltIssuerSecret

- README.md
Fixed apiVersion of sample ingress in README.md
Fixes #94
```doc operator
NONE
```
> fixed apiVersion for ingress in README

- pkg/controller/issuer/core/core_suite_test.go
- pkg/controller/issuer/core/support_test.go
Added test for support find methods.
```other operator
```
> Added test for support find methods

- pkg/cert/source/reconciler.go
- pkg/controller/issuer/revocation/reconciler.go
Improve error handling for edge cases in source and revocation reconciler.
Fixes #
```other operator
NONE
```
> Improve error handling for edge cases

- pkg/controller/issuer/acme/handler.go
- test/functional/basics.go
- test/functional/config/config.go
Fix auto registration for issuer with external account binding.
Fixes #
```bugfix user
Fix auto registration for issuer with external account binding.
```
> Fix auto registration for issuer with EAB

- charts/cert-management/templates/cert.gardener.cloud_certificaterevocations.yaml
- charts/cert-management/templates/cert.gardener.cloud_certificates.yaml
- charts/cert-management/templates/cert.gardener.cloud_issuers.yaml
Fix optional deployment of CRDs
Fixes #
```bugfix operator
Fix optional deployment of CRDs which was broken with release v0.10.8
```
> Fix optional deployment of CRDs

- pkg/cert/legobridge/dnscontrollerprovider.go
Improve message if DNS entry is not ready. The status of DNSEntries are now checked if either they have no provider or the status message is added to the error.
Fixes #
```other user
Improve message if DNS entry is not getting ready.
```
> Improve message if DNS entry is not ready

- pkg/controller/issuer/certificate/reconciler.go
If multiple certificate resources are using the same secret, on renewal not all certificate resource reflect the new expirationDate in the status. This is checked and fixed during the periodic reconciliation.
Fixes #
```other operator
Update expirationDate if secret is shared between certs
```
> Update expirationDate if secret is shared between certs

- .ci/e2etests
- .ci/pipeline_definitions
- .gitignore
Update ci pipeline: add step `e2etests`
Fixes #
```other operator
NONE
```
> Add ci step e2etests

- Makefile
- hack/check-cert-secret.sh
- hack/generate-renovate-ignore-deps.sh
- hack/kind/skaffold-run.sh
- hack/kind/test-functional-local.sh
- pkg/cert/client/scheme.go
- test/utils/generate_cert.go
- test/utils/logbridge.go
- test/utils/pebble.go
Add check for license headers reusing existing tooling from gardener/gardener project.
Missing headers are also fixed.
Fixes #
```other operator
NONE
```
> Add check for license headers and fix missing headers

- go.mod
- go.sum
- test/integration/controller/issuer/issuer_suite_test.go
Redirect and reduce logging for integration tests using controller-manager-library
Fixes #
```other operator
NONE
```
> Reduce logging for integration test

- pkg/cert/legobridge/cakeypair_test.go
- pkg/cert/source/reconciler.go
- pkg/cert/utils/dns_utils_test.go
- pkg/cert/utils/domainrange_test.go
- pkg/cert/utils/issuerkey_test.go
- pkg/cert/utils/utils_certificate_test.go
- pkg/cert/utils/utils_mod.go
- pkg/cert/utils/utils_mod_test.go
- pkg/controller/issuer/certificate/reconciler.go
/kind test
This PR adds several Tests to the Utils files.
Fixes #
NONE
```other operator
NONE
```
**Coverage**
Before this PR: 17.6%
After this PR: 19.2%
> Add Unit Tests to Utils

- pkg/certman2/apis/cert/v1alpha1
- pkg/certman2/client/scheme.go
- pkg/certman2/controller/certificate/add.go
- pkg/certman2/controller/certificate/reconciler.go
- pkg/certman2/controller/certificate/reconciler_delete.go
- pkg/certman2/controller/certificate/reconciler_reconcile.go
- pkg/certman2/controller/issuer/controlplane/acme/handler.go
- pkg/certman2/controller/issuer/controlplane/acme/handler_test.go
- pkg/certman2/controller/issuer/controlplane/add.go
- pkg/certman2/controller/issuer/controlplane/ca/handler.go
- pkg/certman2/controller/issuer/controlplane/ca/handler_test.go
- pkg/certman2/controller/issuer/controlplane/reconciler.go
- pkg/certman2/controller/source/common/certinput.go
- pkg/certman2/controller/source/common/reconcilerbase.go
- pkg/certman2/controller/source/ingress/reconciler_test.go
- pkg/certman2/controller/source/istio_gateway/reconciler_test.go
- pkg/certman2/controller/source/k8s_gateway/reconciler_test.go
- pkg/certman2/controller/source/service/reconciler_test.go
- pkg/certman2/core/issuerDNSSelections.go
- pkg/certman2/core/referencedSecrets_test.go
- pkg/certman2/core/state.go
- pkg/certman2/core/support.go
- test/certman2/integration/controller/issuer/issuer_test.go
- test/certman2/integration/controller/source/source_test.go
/kind cleanup
Drop linked package "github.com/gardener/cert-management/pkg/certman2/apis/cert/v1alpha1"
Fixes #
```other operator
NONE
```
> Drop linked package "github.com/gardener/cert-management/pkg/certman2/apis/cert/v1alpha1"

- pkg/controller/issuer/certificate/reconciler.go
/kind cleanup
Self-explanatory
_n.a._
```other operator
NONE
```
> refactor: Fix typo in function name

- README.md
This PR adds a `Build` badge that refers to the Build Github job.
Slightly related to gardener/gardener#12632
/cc @ialidzhikov 
```other operator
NONE
```
> Add a build badge to the README.md

- charts/cert-management/templates/cert.gardener.cloud_certificates.yaml
- pkg/apis/cert/crds/cert.gardener.cloud_certificates.yaml
- pkg/apis/cert/crds/zz_generated_crds.go
- pkg/apis/cert/v1alpha1/types.go
- pkg/certman2/apis/cert/crd-cert.gardener.cloud_certificates.yaml
Fix typo in `Certificate.spec.FollowCNAME` description.
_n.a._
```other operator
NONE
```
> docs: Fix typo in `Certificate.spec.FollowCNAME` description
