pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/core/support.go
If a certificate is reused with the same name in a second namespace,
it must be copied to the second namespace.
Fixes #2
```improvement user
bug fix: create secret copy if two managed ingress with same TLS hosts and same secret name are defined in two namespaces (issue #2)
```
=> fix reuse of certificate secret with same name in different namespace

pkg/cert/legobridge/dnscontrollerprovider.go, pkg/controller/issuer/certificate/reconciler.go
If certificate is requested for DNS names like `mydomain.com` and `*.mydomain.com`, two DNS challenges are created for `mydomain.com` which need to be presented in a single TXT DNS record.
Additionally, this PR improves the robustness and speed of the DNS challenge validation by waiting for readiness of DNS entries.
Fixes #3
```improvement user
fix multiple DNS challenges for same domain name.
```
```improvement user
wait for readiness of DNSEntries before starting DNS challenge validation. 
```
=> fix multiple DNS challenges for same domain name

examples/40-ingress-echoheaders.yaml, pkg/cert/source/reconciler.go
Fixes #6 
```improvement operator
fix for "Panic if ingress spec.tls.hosts not specified" (issue #6)
```
=> fix panic if an ingress spec does not provide tls hosts

pkg/controller/issuer/certificate/reconciler.go
Existing TLS secret for an ingress may have type `kubernetes.io/tls` and updating
the secret fails, as cert-manage uses type `Opaque` by default.
Fixes #8
```improvement operator
Existing certificate secrets with type `kubernetes.io/tls` can be updated
to simplify migration from cert-broker/cert-manager.
```
=> allow to update certificate secrets with type `kubernetes.io/tls`

pkg/cert/legobridge/certificate.go, pkg/cert/legobridge/dnscontrollerprovider.go, pkg/controller/issuer/certificate/reconciler.go
Fixes #11
```improvement operator
improved behaviour if same certificate is requested multiple times simultaneously
```
=> keep track of pending domain names; check for existing DNSEntry

README.md, charts/cert-management/values.yaml, pkg/cert/legobridge/dnscontrollerprovider.go, pkg/cert/source/controller.go, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/controller.go, pkg/controller/issuer/core/const.go
If there are multiple dns-controller-manager running on the dns cluster,
the dns.gardener.cloud/class has to be set for the challenging dns entry to select the
correct dns-controller-manager.
```improvement operator
new command line option --dns-class to set the dns class for challenging dns entries optionally
```
=> adding command line option --dns-class

pkg/cert/source/defaults.go
If certificate creation fails, the event for the source object should have the event type `warning`.
Fixes #20 
```improvement user
If certificate creation fails, the event for the source object (ingress or service) has now the correct event type `warning`.
```
=> set event type to warning for failed certificate

pkg/cert/source/certinfo.go
The source controllers ignore now certificates and especially their secrets if the controller is no responsible as defined by the `--cert-class` command line option and the corresponding `cert.gardener.cloud/class` annotation in the managed service or ingress resource.
Fixes #23 
```improvement operator
source controllers: ignore certificates for which it  is not responsible
```
=> source controllers: ignore certificates for which it  is not responsible

charts/cert-management/templates/crds.yaml, examples/10-crds.yaml
This PR harmonizes the CRD files in the examples and charts directories. It also adds a 64 char limit to the CRD validation for the `commonName` field. 
```improvement operator
The `commonName` field of certificates is now subjected to a 64 characters limit.
```
=> Enhance CRD validation

charts/cert-management/templates/deployment.yaml, charts/cert-management/values.yaml, hack/generateChartOptions.py, pkg/cert/legobridge/certificate.go, pkg/cert/legobridge/dnscontrollerprovider.go, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/controller.go, pkg/controller/issuer/core/const.go
On Alicloud DNS the DNS record with the DNS challenge is not propagated with the current fixed TTL setting of 30s.
With TTL of 60s it is propagated correctly to public DNS servers.
With this PR, the TTL is set to the propagation timeout of the DNS challenge.
This propagation timeout defaults to 60s.
Additionally it can set with the command line option `--propagation-timeout`.
Fixes #32 
```improvement operator
Fix propagation of DNS entry on Alicloud DNS by setting default TTL to 60s
```
```improvement operator
New command line option `--propagation-timeout`
```
=> make propagation timeout configurable and use it for DNSEntry TTL

go.mod, go.sum, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/controller.go, vendor/modules.txt
Fixes an issue in the controller-manager-library on controller startup with checks of watcher on wrong cluster.
Fixes #
```improvement operator
bug fix for watches check on controller startup in the controller-manager-library
```
=> updated controller-manager-library for startup check issue

.ci/pipeline_definitions
Release notes will be posted to #sap-tech-gardener channel.
As far as I could tell this was the only component that posted release notes to the #k8s-developer-on-duty channel, which was in the meantime moved to a different workspace and hence the channel id changed.
The new channel id and name of the former #k8s-developer-on-duty channel is
`G0172CDN3AS` # gardener-developer-on-duty
If you think the release notes should not be posted to #sap-tech-gardener but instead to #gardener-developer-on-duty I can update the PR accordingly.
Fixes #
```improvement operator
```
=> Update channel name for posting release notes

go.mod, go.sum, pkg/controller/issuer/controller.go, pkg/controller/source/ingress/controller.go, pkg/controller/source/service/controller.go, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/configure.go, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/extension.go, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/interface.go, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/syncer.go, vendor/modules.txt
With this PR the leader election is moved to the default cluster (the seed cluster in Gardener context).
Formerly it was on the source cluster (the shoot cluster), which causes restarts if the network is temporarily not working and the leader election cannot performed.
Fixes #
```improvement operator
move leader election to default cluster, i.e. the control plane
```
=> leader election only on default cluster

charts/cert-management/templates/role-kube-system.yaml, charts/cert-management/templates/rolebinding-kube-system.yaml
add role to access `cluster-identity` configmap in `kube-system` namespace.
Fixes #
```improvement operator
fix helm chart: add role to access configmap `cluster-identity` in `kube-system` namespace.
```
=> role to access cluster-identity

build/Dockerfile, pkg/cert/legobridge/certificate.go, pkg/controller/issuer/certificate/reconciler.go
The secret referenced by a certificate custom resource is not deleted if the certificate CR is deleted, 
because it is unclear if the certificate will be recreated, e.g if the source object has been disappeared temporarily.
With this PR a garbage collection is added which deletes a certificate secret if it is not referenced by a certificate CR and it is outdated at least for 14 days. The garbage collection runs on startup and every 7 days.
Fixes #
```improvement operator
cleanup orphan outdated certificate secrets
```
=> cleanup orphan outdated certificate secrets

docs/installation/setup.md, docs/usage/request_cert.md
As per the new documentation-as-code concept, component-specific documentation resides along the code it describes. Only cross-cutting topics will stay in the /documentation repo.
There's a relative link to dns names guide a the top of the document, which I converted to absolute and pointing to the dns_names.md guide that will be merged with gardener/external-dns-management#140
=> Moving cert management docs from /documentation

README.md, examples/40-ingress-echoheaders.yaml, examples/40-service-loadbalancer.yaml, pkg/cert/source/controller.go, pkg/cert/source/defaults.go, pkg/controller/source/ingress/handler.go
Allow to specify the common name for certificates of services and ingresses explicitly by using an annotation `cert.gardener.cloud/commonname`.
Fixes #48 
```improvement user
optional common name annotation for services and ingresses
```
=> common name annotation for services and ingresses

pkg/controller/issuer/certificate/reconciler.go
This is a fix for a corner case. If a certificate was successfully requested and later the secret data is deleted or corrupt,
the certificate object went to state error, as the validity of the secret could not be checked.
E.g. status of the certificate shows:
```
status:
message: fetching tls.crt from request secret failed
state: Error
```
With this change, the invalid secret data is ignored and processed as if it needs to be renewed.
Fixes #
```improvement operator
renew certificate if its certificate secret is invalid/corrupt instead of going to state error
```
=> renew certificate if its certificate secret is invalid/corrupt instead of going to state error

pkg/controller/issuer/certificate/reconciler.go
The secrets on the source cluster are not cached/watched anymore to reduce the memory footprint.
The secrets on the issuer namespace on the issuer cluster are still watched, but this should be no problem, as it is restricted to a single namespace (control plane namespace).
Fixes #55 
```improvement operator
no caching of secrets on source cluster to reduce memory footprint
```
=> no caching of secrets on source cluster

README.md, charts/cert-management/templates/deployment.yaml, charts/cert-management/values.yaml, hack/generateChartOptions.py, pkg/cert/metrics/metrics.go, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/controller.go, pkg/controller/issuer/core/const.go, pkg/controller/issuer/core/objectnameset.go, pkg/controller/issuer/core/state.go, pkg/controller/issuer/core/support.go
A metrics has been added for certificates whose renewal is overdue. A certificate is 'renewal overdue' if its expire date is within the configurable `--renewal-overdue-window` (default 25 days). 
Besides all specific metrics of the `cert-controller-manager` now have a common prefix for their names.
Fixes #59 
```improvement operator
Use common prefix `cert_management_` for metrics names.
```
```improvement operator
Add metrics `cert_management_overdue_renewal_certificates` to allow alerting for expiring certificates.
```
=> Add metrics for expiring certificates and use common prefix for metric names

README.md, pkg/cert/legobridge/certificate.go, pkg/cert/legobridge/reguser.go, pkg/cert/metrics/metrics.go, pkg/controller/issuer/certificate/backupsecret.go, pkg/controller/issuer/certificate/reconciler.go
Metrics have been added for certificate secrets:
- `cert_management_secrets{classification="backup"}` number of certificate secret backups
- `cert_management_secrets{classification="revoked"}` number of revoked certificate secrets
- `cert_management_secrets{classification="total"}` total number of certificate secrets on the cluster
These metrics are only updated on startup and every 24h during GC of outdated secrets.
Fixes #
```improvement operator
added metrics for certificate secrets
```
=> add metrics for certificate secrets

cmd/cert-controller-manager/main.go, pkg/apis/cert/v1alpha1/register.go, test/functional/basics.go
This PR moves the scheme registration from the `v1alpha1` package to the main initialization functions of the controller.
It mainly eliminates the indirect dependency to the `controller-manager-library` for every component which wants to use the types in `v1alpha1`, e.g. github.com/gardener/gardener-extension-shoot-cert-service.
```improvement operator
NONE
```
=> Move type registration to main init

pkg/cert/legobridge/dnscontrollerprovider.go, pkg/controller/issuer/controller.go
The timeout settings for DNS propagation are too restrictive for Google CloudDNS.
Default dns propagation timeout has been changed from 60s to 120s.
To keep the overall waiting time in a reasonable range, the timeouts of the secondary DNS propagation checks by the lego lib have been reduced.
Fixes #64 
```improvement user
tuning timeouts to better deal with long dns propagation for some DNS backends
```
=> tuning timeouts to better deal with long dns propagation for some backends

pkg/cert/legobridge/certificate.go, pkg/controller/issuer/certificate/reconciler.go
Events for certificate are added to help for debugging configuration issues.
Fixes #63 
```improvement user
events are created on reconciliation of certificate objects
```
=> events for certificate objects

charts/cert-management/templates/clusterrole.yaml
Experienced errors generating certs in soil for gardener dashboard webterminals
Fixes #
```improvement operator
Add certificaterevocations to clusterrole resources
```
=> Update clusterrole to include certificaterevocations

pkg/controller/issuer/certificate/backupsecret.go, pkg/controller/issuer/certificate/reconciler.go
The default secret type of certificate secrets is changed from `Opaque` to `kubernetes.io/tls` to avoid problems with some client applications like contour.
Already existing certificate secrets will keep their original type, as the secret type is immutable. To change the secret type the secret has to been deleted and a reconciliation of the certificate has to be triggered either by restarting the cert-controller-manager or recreating the certificate object.
Fixes #73 
```improvement user
changed default type of certificate secret to `kubernetes.io/tls`
```
=> changed default type of certificate secret to `kubernetes.io/tls`

README.md, charts/cert-management/templates/clusterrole.yaml, charts/cert-management/templates/deployment.yaml, charts/cert-management/templates/role.yaml, charts/cert-management/values.yaml, cmd/cert-controller-manager/main.go, go.mod, go.sum, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease/config.go, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease/lease.go, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/syncer.go, vendor/modules.txt
The cert-controller-manager now uses both configmaps and leases for leader election.
Fixes #
```other operator
using both configmaps and leases for leader election
```
=> using configmaps and leases for leader election

build/Dockerfile, go.mod, pkg/cert/legobridge/cakeypair.go, pkg/cert/legobridge/certificate.go, pkg/cert/legobridge/dnscontrollerprovider.go, pkg/cert/legobridge/pki.go, pkg/cert/legobridge/reguser.go, pkg/cert/utils/utils_certificate.go, pkg/controller/issuer/acme/handler.go, pkg/controller/issuer/ca/handler.go, pkg/controller/issuer/certificate/backupsecret.go, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/core/support.go, pkg/controller/issuer/core/wrappedregistration.go, pkg/controller/issuer/revocation/reconciler.go, test/functional/basics.go, test/functional/config/config.go, test/functional/config/utils.go, vendor/modules.txt
Update of the account registration in the issuer status is not handled correctly if the issuer secret of type `ACME` is updated. 
Besides, the default behaviour is unsuitable for secret rotation, as it triggers an immediate renewal of all certificates.
To allow secret rotation without immediate renewals, all certificate secret hashes are migrated. The new hash includes the issuer key instead of the issuer secret.
Additionally the error handling has been harmonised by replacing `Wrap´ from `github.com/pkg/errors` with `fmt.Errorf("...: %w", err)`
Fixes #
```bugfix operator
[ACME] Fix account registration on issuer secret update and allow secret rotation without …
```
=> [ACME] Fix account registration on issuer secret update

pkg/controller/issuer/acme/handler.go, pkg/controller/issuer/certificate/backupsecret.go, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/core/state.go, pkg/controller/issuer/core/support.go
Avoid requesting new certificates on migration from v0.7.x to v0.8.x for annotated ingress and service resources.
The `Certificate` resource generated for annotated ingress and service resources can loose it labels because of a trigger caused by an update of the issuer secret in the v0.7.x version. An additional migration path has been added to deal with this case.
Fixes #
```bugfix operator
Avoid requesting new certificates on migration from v0.7.x to v0.8.x for annotated ingress and service resources.
```
=> fix for migration of certificate-hash

pkg/controller/issuer/certificate/reconciler.go
If during certificate hash migration the update of a secret fails, a panic occurs because of overwritten variable `obj`.
```
Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x1908a00), concrete:(*runtime._type)(0x1968260), asserted:(*runtime._type)(0x194ff00), missingMethod:""} (interface conversion: abstract.ObjectData is *v1.Secret, not *v1alpha1.Certificate)
...
github.com/gardener/cert-management/pkg/controller/issuer/certificate.(*certReconciler).failed(...)
/build/pkg/controller/issuer/certificate/reconciler.go:1034
github.com/gardener/cert-management/pkg/controller/issuer/certificate.(*certReconciler).migrateSpecHash(0xc000012380, 0x1bd9d40, 0xc0000a89b0, 0x1bec938, 0xc00068c900, 0xc001100400, 0x38, 0xc001100480, …
```
=> fix panic on failed secret update on hash migration

go.mod, go.sum, vendor/github.com/gardener/controller-manager-library/pkg/resources/slavecache.go, vendor/modules.txt
Under rare circumstances the groupkind migration of certificates (replacing owner references of ingresses from `extensions/v1beta1` to `networking.k8s.io/v1beta1`) fails.
This can happen if the generated certificate has become invalid after its custom resource definition introduced a `maxLength` for the subject.
The panic is avoided with the changes of this PR. 
Fixes #
```other operator
No panic on failed groupkind migration
```
=> No panic on failed groupkind migration

charts/cert-management/templates/crds-v1.yaml, charts/cert-management/templates/crds-v1beta1.yaml, cmd/cert-controller-manager/main.go, examples/40-ingress-echoheaders.yaml, go.mod, go.sum, pkg/controller/source/ingress/handler.go, vendor/github.com/gardener/controller-manager-library/pkg/resources/apiextensions/crds.go, vendor/github.com/gardener/controller-manager-library/pkg/resources/apiextensions/versions.go, vendor/modules.txt
Added support for Kubernetes v1.22 as some apiVersions are not available anymore.
Fixes #
```other operator
Support for Kubernetes v1.22
```
=> Support for Kubernetes v1.22

pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/core/support.go
Fix divide by zero on looking up non-existing resource quota.
This may happen if the certificates reconciliation starts before the issuer is updated.
Fixes #91 
```bugfix operator
Fix rare divide by zero on looking up resource quota for uninitialised issuer
```
=> Fix divide by zero on looking up resource quota for uninitialised issuer

README.md, go.mod, go.sum, test/functional/run.sh, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/interface.go, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/lease/config.go, vendor/github.com/gardener/controller-manager-library/pkg/controllermanager/controller/pool.go, vendor/github.com/gardener/controller-manager-library/pkg/resources/abstract/resources.go, vendor/github.com/gardener/controller-manager-library/pkg/resources/subcache.go, vendor/modules.txt
Switch default leader election resource lock from `configmapsleases` to `leases`
```other operator
Switch default leader election resource lock from `configmapsleases` to `leases`
```
=> Switch default leader election resource lock to leases

build/Dockerfile
Build uses golang 1.17.7.
Fixes #
```other operator
```
=> Updating build to golang 1.17.7

README.md, build/Dockerfile, pkg/cert/legobridge/certificate.go, pkg/cert/legobridge/dnscontrollerprovider.go
The message of the event for the certificate object if the certificate request failed has been improved by adding information about the failed check (either `DNS entry getting ready` or `DNS record propagation`).
Fixes #
```other user
Improved message for event on failed DNS challenge
```
=> Improved message for event on failed DNS challenge

build/Dockerfile
/area open-source security
This PR changes the base image for `cert-controller-manager` from `alpine` to [distroless](https://github.com/GoogleContainerTools/distroless). This will reduce the attack surface of the images.
Fixes #
```other operator
The `cert-controller-manager` now uses `distroless` instead of `alpine` as a base image.
```
=> Change base image from alpine to distroless

build/Dockerfile, go.mod, hack/check-cert-secret.sh
Update builder image from golang:v1.18.5 to v1.19.2
Fixes #
```other operator
Update builder image from `golang:1.18.5` to `golang:1.19.2`
```
=> Update builder image from golang:v1.18.5 to v1.19.2

pkg/controller/issuer/core/support.go
This PR fixes a bug in the method FindIssuerKeyByName caused by the "binding per-loop" instead of "binding per-iteration" of for loops in Go.
As a consequence of this bug, a seemingly random issuer was selected if there have been multiple issuers.
Fixes #113
```bugfix user
Fix for correct issuer selection by name.
```
=> Fix FindIssuerKeyByName (binding per-loop bug)

README.md
Documentation for the `followCNAME` option
Fixes #
```doc user
Documentation for the `followCNAME` option
```
=> Documentation for the `followCNAME` option

build/Dockerfile
Update builder image to golang 1.20.2
Fixes #
```other operator
Bump builder image from golang version `1.20.1` to `1.20.2`
```
=> bump builder image to golang-1.20.2

charts/cert-management/templates/deployment.yaml
/area security networking
This PR adapts the `NetworkPolicy`s as following:
- egress traffic to private networks (to reach ACME servers located in private networks)
missed by https://github.com/gardener/cert-management/pull/128
```other operator
NONE
```
=> Adapt 'NetworkPolicy'

README.md, build/Dockerfile, examples/30-cert-simple.yaml, examples/40-ingress-echoheaders.yaml, examples/40-service-loadbalancer.yaml, pkg/cert/source/reconciler.go
For custom issuers you have to specify the annotation `cert.gardener.cloud/issuer annotation` for managed resources like `Ingress` and `Service`.
For shoot issuers (option `--allow-target-issuers`) you have to provide both namespace and name in this case, but the source controller did not deal correctly with it.
Fixes #
```bugfix user
Allow to specify shoot issuer in annotation `cert.gardener.cloud/issuer annotation` with format `namespace/name`.
```
```other operator
Updated builder image from `golang:1.20.5` to `golang:1.20.6`
=> Fix cert.gardener.cloud/issuer annotation for shoot issuers

build/Dockerfile
Bump golang from 1.20.6 to 1.20.7
Fixes #
```other operator
Bump golang from `1.20.6` to `1.20.7`
```
=> Bump golang from 1.20.6 to 1.20.7

Makefile, charts/cert-management/templates/cert.gardener.cloud_certificaterevocations.yaml, charts/cert-management/templates/cert.gardener.cloud_certificates.yaml, charts/cert-management/templates/cert.gardener.cloud_issuers.yaml, hack/copy-crds.sh
This PR adds back the helm labels to CRDs removed in https://github.com/gardener/cert-management/pull/133.
Fixes #
```other operator
NONE
```
=> Add helm labels to CRDs

pkg/controller/issuer/certificate/reconciler.go, test/functional/basics.go
This PR fixes an edge case of an inconsistent certificate: If the certificate has certificate hash labels but the secret is empty, a new certificate is requested now.
Fixes #
```other operator
Fix edge case of inconsistent certificate/secret: request certificate in this case.
```
=> Fix edge case of inconsistent certificate/secret: request certificate in this case

cmd/cert-controller-manager/main.go, pkg/cert/legobridge/dnscontrollerprovider.go
Disable followCNAME by default again, as it was introduced with github.com/go-acme/lego version upgrade from `v4.8.0` to `v4.14.0`(Introduced with https://github.com/go-acme/lego/pull/1718)
Fixes #139 
```other operator
Disable followCNAME by default again as it was activated implicitly by github.com/go-acme/lego version upgrade
```
=> Disable followCNAME by default again

hack/check-cert-secret.sh, pkg/cert/legobridge/cakeypair_test.go, pkg/cert/legobridge/legobridge_suite_test.go, pkg/cert/legobridge/pki.go
For CA issuers only EC and PKCS1 private keys are allowed currently.
With this change also PKCS8 private keys are supported as generated by newer versions of openssl.
Fixes #
```other user
Support PKCS8 private keys for CA issuers
```
=> PKCS8 private keys for CA issuers

charts/cert-management/templates/cert.gardener.cloud_issuers.yaml, pkg/apis/cert/crds/cert.gardener.cloud_issuers.yaml, pkg/apis/cert/crds/zz_generated_crds.go, pkg/apis/cert/v1alpha1/types.go
Fixes https://github.com/gardener/gardener-extension-shoot-cert-service/issues/208
```other operator
Remove `issuer` short name for issuer CustomResourceDefinition as it is the same as the singular.
```
=> Remove short name for issuer

.ci/pipeline_definitions
**What this PR does / why we need it**
Refactor .ci/pipeline_definitions in preparations for subsequent switch from GCR -> Artifact-Registry. This change will as a side-effect make managing pipeline-definition slightly less cumbersome.
Accepting this change will have no immediate effect. Therefore, no release-notes are deemed necessary.
=> Prepare gcr to ar

.ci/pipeline_definitions, Makefile, charts/cert-management/values.yaml
GCR has been deprecated [0] in favour of Artifact-Registry.
Thus, change push-targets for OCI-Images:
- europe-docker.pkg.dev/gardener-project/snapshots for snapshots
- europe-docker.pkg.dev/gardener-project/releases for releases
- europe-docker.pkg.dev/gardener-project/public for combined view of snapshots + releases
[0]
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr
```breaking operator
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.
```
=> switch GCR -> Artifact-Registry

hack/generate-code
Reverts usage of "kube::codegen::gen_*" scripts introduced in #142 to be comparable to other Gardener projects.
Fixes #
```other developer
NONE
```
=> Using common code generation scripts

pkg/cert/source/reconciler.go, pkg/controller/issuer/certificate/reconciler.go
Fix for certificates without common name (if first domain name is longer than 64 characters). On updating existing source objects, the certificates the commonName was filled wrongly.
Additionally the hashcode calculation was wrong if common name was not filled.
Fix for new bug introduced with with #150.
Fixes #
```bugfix user
Updating source objects (like Ingress or Service) with first domain name longer than 64 character failed, as the commonName field was filled in the updated certificate object. It must be left empty in this case.
```
=> Fix updateEntry for first domain len > 64

Dockerfile, go.mod
Bump golang to 1.22.1
Fixes #
```other operator
Bump golang from 1.22.0 to 1.22.1
```
=> Bump golang to 1.22.1

pkg/controller/source/gateways/crdwatch/controller.go, pkg/controller/source/gateways/gatewayapi/controller.go, pkg/controller/source/gateways/istio/controller.go
For multi-cluster deployments, the new source controllers `istio-gateways-dns` and `k8s-gateways-dns` did watch on the default cluster, but the must watch on the source cluster.
Fixes #
```other operator
Fix cluster configuration for new source controllers `istio-gateways-dns` and `k8s-gateways-dns`.
```
=> Fix cluster configuration for new source controllers

pkg/cert/legobridge/certificate.go
/kind bug
Creating a certificate referencing a ca issuer with a given csr creates a nil pointer exception.
Example:
```
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
name: cert-csr
namespace: default
spec:
csr: ......
issuerRef:
name: some-ca-issuer
```
```bugfix user
Creating certificates with a given csr referencing a ca issuer do not throw a nil pointer exception anymore 
```
=> fix creating certificates with a given csr referencing a ca issuer

pkg/cert/legobridge/certificate.go, pkg/cert/legobridge/delegatingprovider.go, pkg/cert/legobridge/reguser.go, pkg/cert/metrics/metrics.go, pkg/cert/utils/issuerinfo.go, pkg/cert/utils/issuerkey.go
Refactoring: introduce issuer key interface to simplify rewrite without controller-manager-library.
Fixes #
```other developer
Refactoring: introduce issuer key interface
```
=> Refactoring: introduce issuer key interface to simplify rewrite

hack/kind/registry/base/registry.yaml
Replace registry image repository, as repo `eu.gcr.io/gardener-project` will disappear soon.
Fixes #
```other operator
NONE
```
=> Replace registry image repository

README.md, docs/usage/tutorials/istio-gateways.md, examples/40-gateway-istio.yaml, examples/40-service-loadbalancer.yaml, pkg/cert/source/controller.go, pkg/cert/source/defaults.go, pkg/cert/source/interface.go, pkg/cert/source/reconciler.go, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/source/gateways/gatewayapi/handler_test.go, pkg/controller/source/gateways/istio/handler.go, pkg/controller/source/gateways/istio/handler_test.go, pkg/controller/source/helper.go, pkg/controller/source/service/handler.go
Istio expects the TLS secret in the namespace of the ingress-gateway POD.
If a `Gateway` resource should be stored in a different namespace, the managed TLS secret will be created in the same namespace. With the added annotation `cert.gardener.cloud/secret-namespace`, it is possible to specify a different namespace. This annotation is only available for Istio `Gateway` resources and `Services` of type `LoadBalancer`.
Fixes #
```feature user
Istio gateways: Allow to specify namespace for TLS secret by annotation `cert.gardener.cloud/secret-namespace`.
```
=> Istio gateways: Allow to specify namespace for TLS secret

hack/kind/dns-controller-manager/dns-controller-manager-up.sh
I ran `make kind-up` which failed for me at:
```shell
hack/kind/dns-controller-manager/dns-controller-manager-up.sh: line 23: wget: command not found
```
Of course, it'd be easy to install `wget` but as `curl` is used everywhere else in the project and can serve the same purpose it could be a quick fix.
_n.a._
```other operator
NONE
```
=> chore: Use curl instead of wget

.github/pull_request_template.md
It extends the PR template to include a section for categorizing PRs using the `/kind` command.
_n.a._
I noticed that you added missing `kind/*` labels to my PRs twice, so I figured having the reminder in the PR template would make sense. It's copied from https://github.com/gardener/gardener/blob/master/.github/pull_request_template.md?plain=1 and left out the `/area` categorization.
```other operator
NONE
```
=> chore: Add /kind to PR template

go.mod, go.sum, test/integration/controller/issuer/issuer_suite_test.go, test/integration/controller/issuer/issuer_test.go, test/utils/generate_cert.go, test/utils/logbridge.go, test/utils/pebble.go
/kind test
The integration test skeleton added with #315 currently uses the Let's Encrypt ACME staging service.
While it can be safely assumed that this service should be relatively stable it means that the integration tests are making calls to the internet and effectively depend on an external service. Furthermore, we cannot skip the DNS-01 challenge in integration tests as the staging service would enforce passed challenges.
[Pebble](https://github.com/letsencrypt/pebble) is a small ACME server intended to be run for testing purposes. It's already used in the functional E2E tests. This PR invokes the code to start the Pebble ACME server locally during the integration test suite startup.
**Which …
=> test: Use Pebble as the ACME server in integration tests

renovate.json5
We usually close Renovate's pull requests for updating the [`controller-runtime/setup-envtest`](https://github.com/kubernetes-sigs/controller-runtime/tree/main/tools/setup-envtest) digest:
https://github.com/gardener/cert-management/pulls?q=sort%3Aupdated-desc+is%3Apr+%22sigs.k8s.io%2Fcontroller-runtime%2Ftools%2Fsetup-envtest%22+
In the [gardener/gardener](https://github.com/gardener/gardener) repository Renovate is configured to:
* ask for manual approval when it comes to major and minor updates of the `controller-runtime`
* ignore updates for the `setup-envtest` digest as it should be kept in sync (i.e. compatible) with the version of `controller-runtime` being used …
=> chore: Improve Renovate configuration for controller-runtime

charts/cert-management/templates/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/zz_generated_crds.go, pkg/apis/cert/v1alpha1/types.go, pkg/apis/cert/v1alpha1/zz_generated.deepcopy.go, pkg/cert/legobridge/certificate.go, pkg/cert/legobridge/pki.go, pkg/controller/issuer/certificate/reconciler.go
This PR cherry-picks commits from #228 and introduces the `Duration` field on the `Certificate` resource.
It allows you to specify the certificate's lifetime. Issuers, like Let's Encrypt, may ignore this field.
As a secondary goal, by extracting the changes around the duration of certificates from #228 its changeset should become smaller and focused around the introduction of the self-signed issuer.
_n.a._
```feature user
The certificate resource can now define a duration (the lifetime of the certificate). The issuer (especially Let's Encrypt) may ignore this field.
```
=> feat: Introduce certificate duration

test/functional/basics.go
/kind flake
Fix flaky check for keystore data in certificate secret.
Fixes #
```other operator
NONE
```
=> Fix flaky check for keystore data in secret

test/functional/basics.go
/kind flake
Fix flaky check for keystore data in certificate secret.
Fixes #
Followup of https://github.com/gardener/cert-management/pull/366
```other operator
NONE
```
=> Fix flaky check for keystore data in secret (2. try)

pkg/cert/legobridge/pki_test.go, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/reconciler.go, test/integration/controller/issuer/issuer_suite_test.go, test/integration/controller/issuer/issuer_test.go
/kind bug
If a cert-manager controller is killed for any reason during there is a certificate with state `Pending`, the resource will stay in this state forever.
This PR provides a fix for this edge case.
Fixes #
```bugfix operator
Cleanup status for orphan pending certificate resources
```
=> Cleanup status for orphan pending certificate resources

pkg/controller/issuer/acme/handler.go, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/core/support.go, pkg/controller/issuer/reconciler.go, test/integration/controller/issuer/issuer_test.go
/kind bug
After introducing self-signed issuers (PR #228 ) a regression bug was introduced if a certificate references a target issuer (shoot issuer) but target issuer are not allowed by command-line option `--allow-target-issuer=false`.
Fixes #
```bugfix operator
Fix panic if target issuer referenced but not allowed
```
=> Fix panic if target issuer referenced but not allowed

README.md
This PR documents the gaps between the ☸️ community [`cert-manager`](https://[cert-manager](https://cert-manager.io/).io/) and 🧑‍🌾 Gardener's [`cert-management`](https://github.com/gardener/cert-management) (Similar to the list of differentiating features documented in [external-dns-management](https://github.com/gardener/external-dns-management#why-not-using-the-community-external-dns-solution)).
It is not intended to point out a lack of features in either project but rather to document the differences to provide an easy lookup reference. It also allows us to revisit the list in the future to see whether the projects are more closely aligned.
_n.a._
**Special notes …
=> docs: Document gaps to the community `cert-manager`

examples/30-cert-simple.yaml, pkg/cert/legobridge/certificate.go, pkg/cert/legobridge/dnsrecordprovider.go, pkg/cert/source/controller.go, pkg/cert/source/utils.go, pkg/controller/issuer/certificate/reconciler.go
Allow to specify the extension class for a DNS challenge using `DNSRecords` by setting the annotation `cert.gardener.cloud/dnsrecord-class`. It is needed for Gardener internal purposes only. If a `Certificate` is created on the Garden runtime cluster, the `TXT` record for the DNS challenge is created via `DNSRecords` resources. Only `DNSRecords` with `.spec.class=garden` will be managed by the provider extension running there.
Fixes #
```other operator
Support `DNSRecord.spec.class` by annotation `cert.gardener.cloud/dnsrecord-class`
```
=> Support `DNSRecord.spec.class` by annotation `cert.gardener.cloud/dnsrecord-class`

pkg/apis/cert/v1alpha1/state.go, pkg/cert/legobridge/certificate.go, pkg/controller/issuer/certificate/reconciler.go
/kind bug
If two certificates with the same set of domain names are created at the same time, they are reconciled often and use up the certificate request quota ("request quota per day").
This is a fix to count the reconciliation only if all preconditions for the request are fulfilled.
Fixes #
```bugfix user
Fix exhaustion of request quotas on concurrent certificates with same domain name
```
=> Fix exhaustion of request quotas on concurrent certificates with same domain name

test/integration/controller/issuer/issuer_test.go
/kind flake
Higher timeout for orphan certificate reconciliation as it seems to be too short in some integration test runs.
Fixes #
```other operator
NONE
```
=> Integration test: Higher timeout for orphan cert reconciliation

Makefile
/kind test
The Make target `test-integration` is duplicated due to a merge artifact.
This PR dedupes the `test-integration` target.
Follow-up to #426
```other operator
NONE
```
=> fix: Dedupe Make test-integration target

.ci/pipeline_definitions, .ci/verify, Makefile
This PR intends to unify how `make format` works between the Cert- & DNS-management repositories.
_n.a._
Related PRs:
* https://github.com/gardener/external-dns-management/pull/426
* https://github.com/gardener/gardener-extension-shoot-cert-service/pull/360
* https://github.com/gardener/gardener-extension-shoot-dns-service/pull/451
```other operator
NONE
```
=> ci: Unify `make format`

README.md
This PR documents how to trigger a manual `Certificate` renewal using the `.spec.renew` field.
_n.a._
Today, most readers would only learn about this mechanism through the `CertificateRevocation` resource which also supports the `renew` field. However, you don't need a `CertificateRevocation` to renew your `Certificate` as you can achieve the same on the resource itself.
/cc @MartinWeindel @LucaBernstein
```doc user
Added documentation for triggering a manual `Certificate` renewal.
```
=> docs: Document triggering a manual certificate renewal

Makefile
/kind cleanup
The `verify-extended` target was introduced with #442. It executes all tests although there are already executed by separate prow jobs.
I suggest to drop them here again.
/invite @marc1404 
Fixes #
```other operator
NONE
```
=> Drop tests from verify-extended target

charts/cert-management/templates/cert.gardener.cloud_certificaterevocations.yaml, charts/cert-management/templates/cert.gardener.cloud_certificates.yaml, charts/cert-management/templates/cert.gardener.cloud_issuers.yaml, hack/copy-crds.sh
/kind bug
The Helm values `createCRDs.certificates` and `createCRDs.issuers` need to be considered on deploying the CustomResourceDefinitions in the charts.
As the CRDs are updated in `make generate`, the script has been extended.
Fixes #
```other operator
Add condition for deployment of CRDs in Helm charts
```
=> Add condition for deployment of CRDs in Helm charts

pkg/controller/issuer/certificate/reconciler.go, pkg/shared/legobridge/certificate.go, pkg/shared/legobridge/pki.go, pkg/shared/legobridge/pki_test.go, test/integration/controller/issuer/certificate_test.go
/kind bug
This PR addresses the issue described in #446.
When using anything but the default key algorithm and size, the certificate status fluctuates between `PENDING` and `READY`. The controller is provisioning the certificate repeatedly because the stored hash on the certificate resource does not match the hash calculated based on the spec. This is because the hash considers the key size of the certificate if anything but the default is used. Currently, the code for creating certificates from a CA issuer does not propagate the specified key type and ends up using the default algorithm and size.
**Changes in this PR:**
* Propagate the key type through `ObtainInput` and `ObtainOutput` of the CA certificate flow
* Use …
=> fix: Key algorithm and bit size in self-signed certs from CA

charts/cert-management/templates/clusterrole.yaml
/kind bug
Setting only `issuerUseDnsrecords: true` in the values of the Helm chart, leads to a broken deployment, where the cert-controller-manager wants to use `DnsRecords` but does not have permission to access the resource. This PR updates the Helm chart to also equip the `ClusterRole` with the correct permissions in this case.
Fixes #
```bugfix operator
fix: ClusterRole needs dnsrecord permissions when issuerUseDnsrecords is true
```
=> fix: ClusterRole needs dnsrecord permissions when issuerUseDnsrecords is true

charts/cert-management/templates/deployment.yaml
This PR sets the `securityContext.allowPrivilegeEscalation` field to `false` for every container, which does not have `securityContext.Privileged` set to `true` or one of `CAP_SYS_ADMIN/SYS_ADMIN` capabilities added.
Part of gardener/gardener#11139
NONE
```other operator
Containers, which do not require privilege escalations, now forbid privilege escalations explicitly.
```
=> Forbid privilege escalations for component containers

Makefile
/kind test
Currently, only the integration tests of `certman2` are visible in Prow and the Testgrid:
https://testgrid.k8s.io/cert-management#ci-cert-management-integration
This is due to the integration test suites of the legacy and new code line being run sequentially through two commands:
https://github.com/gardener/cert-management/blob/a01bb4e6acafc99206c977874ab1de06652e78b7/Makefile#L86-L87
The `test-integration.sh` is implemented to (over)write the `junit.xml` artifact file, hence only the latter test results are visible.
This PR runs both integration tests together in one command, which results in a single `junit.xml` containing all results.
_n.a._
**Special notes for your …
=> ci: Run integration tests in one command

go.mod, go.sum, hack/tools.go, renovate.json5
/kind cleanup
Drop tools dependency `sigs.k8s.io/controller-runtime/tools/setup-envtest` as it is not needed to run the integration tests. Seems to be some legacy stuff.
Fixes #
```other operator
NONE
```
=> Drop tools dependency `sigs.k8s.io/controller-runtime/tools/setup-envtest`

charts/cert-management/templates/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/zz_generated_crds.go, pkg/apis/cert/v1alpha1/types.go, pkg/apis/cert/v1alpha1/zz_generated.deepcopy.go, pkg/certman2/apis/cert/crd-cert.gardener.cloud_certificates.yaml, pkg/controller/issuer/certificate/reconciler.go, test/integration/controller/issuer/certificate_test.go
/kind api-change
/kind task
This PR adds a `cert.gardener.cloud/not-before` annotation and a new field `issuanceDate` to the `Certificate` status.
The change is analogous to the `cert.gardener.cloud/not-after` annotation and `expirationDate` field.
As the name indicates, the annotation and field capture the `NotBefore` field of an [x509.Certificate](https://github.com/golang/go/blob/1cc624fd6265abe16de78e9cd84272435156aa72/src/crypto/x509/x509.go#L703).
Example output of `kubectl get -owide`:
```terminal
k get cert cert-selfsigned -n default -owide
NAME              COMMON NAME        ISSUER              STATUS   ISSUANCE_DATE          EXPIRATION_DATE        DNS_NAMES   AGE
cert-selfsigned   ca1.mydomain.com …
```
=> feat: Add `IssuanceDate` to `Certificate` status

pkg/controller/issuer/certificate/reconciler.go
/kind cleanup
Rename function parameter `secret` to `secretRec`.
Follow-up to: https://github.com/gardener/cert-management/pull/489#discussion_r2073026788
```other operator
NONE
```
=> refactor: Rename `secret` to `secretRec`

Makefile, cmd/cert-controller-manager/.import-restrictions, cmd/certman2/.import-restrictions, pkg/apis/.import-restrictions, pkg/cert/.import-restrictions, pkg/certman2/.import-restrictions, pkg/client/.import-restrictions, pkg/controller/.import-restrictions, pkg/shared/.import-restrictions, test/certman2/.import-restrictions, test/functional/.import-restrictions, test/integration/.import-restrictions
/kind task
This PR:
- Adds a new Make target `check-imports` that runs [import-boss](https://pkg.go.dev/k8s.io/gengo/examples/import-boss) to enforce rules set by `.import-restrictions` files.
- It's integrated into Make `check`.
- It adds `.import-restrictions` to top-level folders in `cmd`, `pkg`, and `test`
The main goal is to prevent cross-imports from `certman2` to the legacy code and vice versa.
Fixes #476
```other operator
NONE
```
=> chore: Enforce import restrictions through import-boss

README.md, examples/30-cert-selfsigned.yaml, pkg/controller/issuer/controller.go
/kind cleanup
Currently, the documentation specifies that the minimum duration of a `Certificate` must be greater than `720h` or `1440h`. Neither is correct. The minimum duration is **at least** twice the configured renewal window (30 days by default):
https://github.com/gardener/cert-management/blob/4e33a067612a272bd2b8d9668e1bbe9a404d102d/pkg/controller/issuer/certificate/reconciler.go#L842
That means the minimum duration of a `Certificate` with a default renewal window of 30 days is:
`2 * 30d = 1440h`
Relates to: https://github.com/gardener/cert-management/issues/492
```doc user
Documented the correct minimum …
```
=> docs: Document correct minimum duration

charts/cert-management/templates/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/zz_generated_crds.go, pkg/apis/cert/v1alpha1/types.go, pkg/certman2/apis/cert/crd-cert.gardener.cloud_certificates.yaml, pkg/controller/issuer/certificate/reconciler.go, test/integration/controller/issuer/issuer_test.go
/kind cleanup
I forgot to adapt the `Certificate.spec.Duration` field description as well as the error message that the certificate reconciler shows for the minimum duration.
Follow-up to: #495 
```other operator
NONE
```
=> docs: Reformulate minimum `Certificate` duration description

README.md, charts/cert-management/templates/cert.gardener.cloud_certificates.yaml, examples/30-cert-ca.yaml, examples/30-cert-selfsigned.yaml, pkg/apis/cert/crds/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/zz_generated_crds.go, pkg/apis/cert/v1alpha1/types.go, pkg/apis/cert/v1alpha1/zz_generated.deepcopy.go, pkg/certman2/apis/cert/crd-cert.gardener.cloud_certificates.yaml, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/certificate/utils.go, pkg/controller/issuer/certificate/utils_test.go, pkg/shared/legobridge/certificate.go, pkg/shared/legobridge/pki.go, test/integration/controller/issuer/certificate_test.go
/kind api-change
/kind task
This PR extends support for subject alternative names (SANs) in the `Certificate` spec.
The following fields are added:
- `.spec.emailAddresses`
- `.spec.ipAddresses`
- `.spec.uris`
Additionally, SANs can be specified in certificate signing requests (CSRs).
Fixes #449 
```feature user
Added support for subject alternative names (SANs) in the `Certificate` spec and certificate signing requests (CSRs). The following SANs have been added: `emailAddresses`, `ipAddresses`, and `uris`.
```
=> feat: Add SAN fields in Certificate spec

pkg/certman2/controller/certificate/add.go, pkg/certman2/controller/certificate/predicate.go, pkg/certman2/controller/certificate/predicate_test.go, pkg/certman2/controller/certificate/reconciler.go, pkg/certman2/controller/certificate/reconciler_reconcile.go, pkg/certman2/controller/certificate/reconciler_reconcile_test.go, pkg/certman2/controller/certificate/reconciler_test.go, renovate.json5
/kind task
This PR is part of the larger [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) rewrite of this project.
The new implementation using `controller-runtime` is kept in a separate folder and executable binary.
This PR adds the following changes to the `Certificate` controller:
* Handling of orphaned, pending `Certificate`s.
* Backoff handling on `Certificate`s.
* Logging of changed status messages as `Event`s on the `Certificate`.
* Filter pending `Certificate`s using a predicate.
* Adding support for the operator reconcile annotation.
Part of #453
```other operator
NONE
```
=> feat: Extend Certificate controller implementation using controller-runtime

.github/workflows/release.yaml
/kind task
Write permissions are added to the release workflow.
Fixes #
Similar to https://github.com/gardener/external-dns-management/pull/593
```other operator
NONE
```
=> Add write permissions for release workflow

renovate.json5
/area dev-productivity
Uses the shared Renovate preset for grouping Go updates:
https://github.com/gardener/ci-infra/blob/master/config/renovate/group-go-updates.json5
Follow-up to:
* https://github.com/gardener/gardener-extension-shoot-cert-service/pull/452
_n.a._
```other operator
NONE
```
=> chore: Use Renovate preset for grouping Go updates

README.md, charts/cert-management/templates/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/cert.gardener.cloud_certificates.yaml, pkg/apis/cert/crds/zz_generated_crds.go, pkg/apis/cert/v1alpha1/types.go, pkg/apis/cert/v1alpha1/zz_generated.deepcopy.go, pkg/certman2/apis/cert/crd-cert.gardener.cloud_certificates.yaml, pkg/controller/issuer/certificate/reconciler.go, pkg/controller/issuer/core/state.go, pkg/controller/issuer/core/support.go, test/integration/controller/issuer/certificate_test.go
/kind task api-change enhancement
Introduces new fields in the `Certificate` resource:
* `.spec.renewBefore`
* `.status.renewalDate`
The field `renewBefore` allows controlling the renewal window on the level of the `Certificate`.
It specifies a duration that is subtracted from the issued certificate's expiration date to calculate the renewal date.
The planned renewal date is announced in the status of the `Certificate`.
Even when no `renewBefore` is given, the `.status.renewalDate` field will always be populated.
Fixes #492
```feature user
Introduced new `Certificate` fields: `.spec.renewBefore`, …
```
=> feat: Implement `renewBefore` for certificates
